<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Waybill_leftPane_div_full</name>
   <tag></tag>
   <elementGuidId>be624c90-0802-4380-ba61-10201e66782d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>Sidebar-module_root_3mUZs</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
