<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AARCarType</name>
   <tag></tag>
   <elementGuidId>fbced66f-6638-4c1f-8d49-7740bbe64933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid=&quot;aar-car-type&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid=&quot;aar-car-type&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid=&quot;aar-car-type&quot;]</value>
   </webElementProperties>
</WebElementEntity>
