<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply</name>
   <tag></tag>
   <elementGuidId>5c1e69a2-165f-49e8-9a70-488f5537a66e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--primary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex--col App-module_appRoot_2W_oY&quot;]/div[@class=&quot;flex__item App-module_routesRoot_W33fJ&quot;]/section[@class=&quot;flex flex__item flex--col&quot;]/section[@class=&quot;flex flex--row&quot;]/div[@class=&quot;Sidebar-module_root_3mUZs flex__item flex flex--col&quot;]/div[@class=&quot;flex__item QueryController-module_root_2pvTU&quot;]/div[@class=&quot;flex flex--middle QueryController-module_searchWrapper_EoEJG&quot;]/div[@class=&quot;QueryController-module_filterWrapper_3pKH0&quot;]/div[@class=&quot;Popup-module_root_2fCFN FilterMenu-module_root_85JF5&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;QueryController-module_filterContentWrapper_3WheQ&quot;]/div[@class=&quot;QueryController-module_filterFooter_2TfNT u-pt flex flex--row flex--right&quot;]/button[@class=&quot;btn btn--primary&quot;]</value>
   </webElementProperties>
</WebElementEntity>
