<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>createNewRuleOfferButton</name>
   <tag></tag>
   <elementGuidId>b803925d-2cc6-460c-a5e7-45e7c9289102</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>*//button[@data-testid='add-new-rule15-offerings-btn']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
