<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>offeringRoadLastNameInputField</name>
   <tag></tag>
   <elementGuidId>dd6ef54e-e1c7-4368-a2f9-f8f70b4116a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>offeringRailroad.officerLastName</value>
   </webElementProperties>
</WebElementEntity>
