<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>receivingRoadTelephoneInputField</name>
   <tag></tag>
   <elementGuidId>3b8c7866-55e2-45d2-8e29-c0d341cbb878</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>receivingRailroad.telephone</value>
   </webElementProperties>
</WebElementEntity>
