<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>equipment_carkind</name>
   <tag></tag>
   <elementGuidId>824a0594-2141-4646-8036-b02c8bc842d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//span[@data-testid='car-kind']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
