<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>equipment_aarcar_type</name>
   <tag></tag>
   <elementGuidId>87e428a9-1ef9-488e-a56c-bd24732048ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//span[@data-testid='aar-car-type']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
