<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>loco_capacity_speed_minspeed</name>
   <tag></tag>
   <elementGuidId>d5cd765a-19de-4a6f-b6b9-0559bae9a38a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//div[@data-testid='equipment-capacity-and-speed']/div/div[2]/div/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
