<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>loco_clearence</name>
   <tag></tag>
   <elementGuidId>c8f0c6b3-3418-4ac1-98f4-3a56ced53cbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//div[@data-testid='equipment-dimension-details']/div/div[2]/div/div/span
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
