<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>railcar_capacity_grade</name>
   <tag></tag>
   <elementGuidId>25b3d594-df8e-4748-8473-fd96a371800b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//div[@data-testid='equipment-capacity-and-speed']/div/div[2]/div[3]/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
