<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>waybill_shipper_name_rightpane</name>
   <tag></tag>
   <elementGuidId>3cf60600-7c22-4005-a08c-c343e5897888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//*[contains(@data-testid,'waybill-customer-details')]//following::span[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@data-testid,'waybill-customer-details')]//following::span[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
