<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>waybill_status</name>
   <tag></tag>
   <elementGuidId>9ff0b902-2b4a-4d20-be6b-f32bc047ed4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//*[contains(@data-testid,'waybill-form')]//following::span[6]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@data-testid,'waybill-form')]//following::span[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
