<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>px-app-nav_AppNav-module_root_</name>
   <tag></tag>
   <elementGuidId>b30e003d-a77f-44e6-bc3e-a5697e077c1f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>px-app-nav</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AppNav-module_root_3r7aj</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex--col App-module_appRoot_2W_oY&quot;]/header[@class=&quot;AppHeader-module_root_29OSo&quot;]/px-app-nav[@class=&quot;AppNav-module_root_3r7aj&quot;]</value>
   </webElementProperties>
</WebElementEntity>
