<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>px-tab_EDI</name>
   <tag></tag>
   <elementGuidId>a475c9c6-995d-4df3-8992-504052bb013a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//px-tab[(text() = 'EDI' or . = 'EDI')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@data-testid,'waybill-form')]//following::px-tab[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>px-tab</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PxTabs-module_tabRoot_Ucv9w</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EDI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex--col App-module_appRoot_2W_oY&quot;]/div[@class=&quot;flex flex--col flex__item App-module_routesRoot_W33fJ&quot;]/section[@class=&quot;flex flex--col flex__item&quot;]/section[@class=&quot;flex__item flex flex--row PageContent-module_root_24nnp&quot;]/section[@class=&quot;flex__item flex flex--col&quot;]/px-tabs[@class=&quot;PxTabs-module_tabsRoot_-vBzT u-mt&quot;]/px-tab[@class=&quot;PxTabs-module_tabRoot_Ucv9w&quot;]</value>
   </webElementProperties>
</WebElementEntity>
