<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>overWeightCalc</name>
   <tag></tag>
   <elementGuidId>f1ce9c47-5ef3-4c87-93d5-3881f0e782e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name=&quot;totalWeightForOverweightCalculations&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name=&quot;totalWeightForOverweightCalculations&quot;]</value>
   </webElementProperties>
</WebElementEntity>
