<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tolerenceWeight</name>
   <tag></tag>
   <elementGuidId>96cf134f-cfbe-474d-80e7-6c3ade205b66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name=&quot;totalWeightIncludingTolerance&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name=&quot;totalWeightIncludingTolerance&quot;]</value>
   </webElementProperties>
</WebElementEntity>
