<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>weightOnRail</name>
   <tag></tag>
   <elementGuidId>86405f3b-6793-4b3e-be46-dfce38556912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='totalWeightOnRailInThousands']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='totalWeightOnRailInThousands']</value>
   </webElementProperties>
</WebElementEntity>
