<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SaveTrackButton</name>
   <tag></tag>
   <elementGuidId>7e8a064d-2655-4c79-8b8d-be2f8155d5e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//button[@data-testid='save-track']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
